const cfg=window.CINEVERSE_CONFIG||{};const API_URL=(cfg.apiUrl||'').replace(/\/$/,'');const API_ROOT=API_URL.replace(/\/movies\/?$/,'');const TOKEN_KEY='cineverse.idToken';const VERIFIER_KEY='cineverse.pkce';const STATE_KEY='cineverse.state';let allMovies=[];let filtered=[];let nextToken=null;let activeMovie=null;let watchlist=new Map();let searchTimer;
const $=s=>document.querySelector(s);const grid=$('#movieGrid'),loading=$('#loadingState'),empty=$('#emptyState'),error=$('#errorState'),toast=$('#toast');
function token(){return sessionStorage.getItem(TOKEN_KEY)}function claims(){try{return JSON.parse(atob(token().split('.')[1].replace(/-/g,'+').replace(/_/g,'/')))}catch{return null}}function loggedIn(){const c=claims();return !!c&&c.exp*1000>Date.now()}function headers(){const t=token();return t?{Authorization:`Bearer ${t}`}:{}}
function notify(message,isError=false){toast.textContent=message;toast.className=`toast show${isError?' error':''}`;clearTimeout(notify.t);notify.t=setTimeout(()=>toast.className='toast',3200)}
function poster(movie){const url=movie.PosterUrl||movie.posterUrl;return url?`<img src="${escapeAttr(url)}" alt="Poster for ${escapeHtml(movie.MovieName||'Untitled')}" loading="lazy">`:`<div class="poster-fallback" aria-label="No poster available">${escapeHtml((movie.MovieName||'CV').slice(0,2).toUpperCase())}</div>`}
function escapeHtml(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function escapeAttr(v){return escapeHtml(v).replace(/`/g,'&#096;')}
async function api(url,options={}){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',...headers(),...(options.headers||{})}});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data}
async function loadMovies(reset=true){if(reset){loading.classList.remove('hidden');empty.classList.add('hidden');error.classList.add('hidden');grid.innerHTML='';nextToken=null}try{const url=new URL(API_URL);url.searchParams.set('limit','60');if(nextToken)url.searchParams.set('nextToken',nextToken);const data=await api(url);if(reset)allMovies=[];allMovies.push(...(data.data||data.movies||[]));nextToken=data.nextToken||null;hydrateFilters();applyFilters();loading.classList.add('hidden');$('#heroCount').textContent=allMovies.length+(nextToken?'+':'')}catch(e){loading.classList.add('hidden');error.classList.remove('hidden');$('#errorMessage').textContent=e.message||'The catalog could not be reached.'}}
function hydrateFilters(){const genres=[...new Set(allMovies.flatMap(m=>String(m.Genre||'').split(',').map(x=>x.trim()).filter(Boolean)))].sort();const years=[...new Set(allMovies.map(m=>Number(m.ReleaseYear)).filter(Boolean))].sort((a,b)=>b-a);const g=$('#genreFilter'),y=$('#yearFilter'),oldG=g.value,oldY=y.value;g.innerHTML='<option value="">All genres</option>'+genres.map(x=>`<option>${escapeHtml(x)}</option>`).join('');y.innerHTML='<option value="">Any year</option>'+years.map(x=>`<option>${x}</option>`).join('');g.value=genres.includes(oldG)?oldG:'';y.value=years.map(String).includes(oldY)?oldY:''}
function applyFilters(){const q=$('#searchInput').value.trim().toLowerCase(),genre=$('#genreFilter').value,year=$('#yearFilter').value,rating=Number($('#ratingFilter').value||0),sort=$('#sortFilter').value;filtered=allMovies.filter(m=>{const hay=[m.MovieName,m.Genre,m.Director,m.Language,m.Overview].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!genre||String(m.Genre||'').toLowerCase().split(',').map(x=>x.trim()).includes(genre.toLowerCase()))&&(!year||String(m.ReleaseYear)===year)&&(!rating||Number(m.Rating||0)>=rating)});filtered.sort((a,b)=>sort==='rating'?Number(b.Rating||0)-Number(a.Rating||0):sort==='newest'?Number(b.ReleaseYear||0)-Number(a.ReleaseYear||0):sort==='title'?String(a.MovieName||'').localeCompare(String(b.MovieName||'')):Number(b.Rating||0)*10+Number(b.ReleaseYear||0)/100-Number(a.Rating||0)*10-Number(a.ReleaseYear||0)/100);$('#resultCount').textContent=`${filtered.length} ${filtered.length===1?'title':'titles'}`;renderMovies()}
function renderMovies(){grid.innerHTML=filtered.map(movieCard).join('');empty.classList.toggle('hidden',filtered.length>0);if(!filtered.length)grid.innerHTML='';$('#loadMore').classList.toggle('hidden',!nextToken||!!$('#searchInput').value.trim())}
function movieCard(m){const id=escapeAttr(m.MovieId||'');const saved=watchlist.has(m.MovieId);const meta=[m.ReleaseYear,m.Language].filter(Boolean).join(' · ');return `<article class="movie-card" tabindex="0"><button class="open-hit" data-open="${id}" aria-label="Open details for ${escapeHtml(m.MovieName||'Untitled')}"></button><div class="poster">${poster(m)}${m.Rating!==undefined?`<span class="rating-badge">★ ${Number(m.Rating).toFixed(1)}</span>`:''}<button class="save-button ${saved?'saved':''}" data-save="${id}" aria-label="${saved?'Remove from':'Add to'} watchlist" type="button">${saved?'♥':'♡'}</button></div><div class="movie-info"><div class="movie-title">${escapeHtml(m.MovieName||'Untitled')}</div><div class="movie-meta">${escapeHtml(meta||'Details available')}</div>${m.Genre?`<span class="movie-genre">${escapeHtml(String(m.Genre).split(',')[0].trim())}</span>`:''}</div></article>`}
document.addEventListener('click',e=>{const open=e.target.closest('[data-open]');if(open){const m=allMovies.find(x=>x.MovieId===open.dataset.open);if(m)openMovie(m)}const save=e.target.closest('[data-save]');if(save){e.preventDefault();toggleWatchlist(save.dataset.save)}});
function openMovie(m){activeMovie=m;$('#dialogTitle').textContent=m.MovieName||'Untitled';$('#dialogMeta').textContent=[m.ReleaseYear,m.Director,m.Language].filter(Boolean).join(' · ')||'CINEVERSE TITLE';$('#dialogOverview').textContent=m.Overview||m.Remark||'A movie in your CineVerse catalog. Explore the metadata, save it for later, and discover your next favorite.';$('#dialogPills').innerHTML=[m.Rating?`★ ${Number(m.Rating).toFixed(1)}/10`:null,m.Runtime?`${m.Runtime} min`:null,m.Genre].filter(Boolean).map(x=>`<span>${escapeHtml(x)}</span>`).join('');$('#dialogPoster').innerHTML=poster(m);const saved=watchlist.has(m.MovieId);$('#dialogWatchlist').textContent=saved?'♥ Saved to watchlist':'♡ Add to watchlist';$('#movieDialog').showModal()}
async function toggleWatchlist(id){if(!loggedIn()){openAuth();return}try{if(watchlist.has(id)){await api(`${API_ROOT}/watchlist/${encodeURIComponent(id)}`,{method:'DELETE'});watchlist.delete(id);notify('Removed from your watchlist')}else{await api(`${API_ROOT}/watchlist/${encodeURIComponent(id)}`,{method:'PUT'});watchlist.set(id,allMovies.find(m=>m.MovieId===id)||{MovieId:id});notify('Added to your watchlist')}renderMovies();renderWatchlist();if(activeMovie&&activeMovie.MovieId===id)$('#dialogWatchlist').textContent=watchlist.has(id)?'♥ Saved to watchlist':'♡ Add to watchlist'}catch(e){notify(e.message,true)}}
async function loadWatchlist(){if(!loggedIn()){watchlist.clear();renderWatchlist();return}try{const d=await api(`${API_ROOT}/watchlist`);watchlist=new Map((d.data||[]).map(m=>[m.MovieId,m]));renderWatchlist();renderMovies()}catch(e){notify('Could not load your watchlist',true)}}
function renderWatchlist(){const items=[...watchlist.values()].map(x=>allMovies.find(m=>m.MovieId===x.MovieId)||x);$('#watchlistGrid').innerHTML=items.map(movieCard).join('');$('#watchlistEmpty').classList.toggle('hidden',items.length>0);$('#watchlistCount').textContent=loggedIn()?`${items.length} saved ${items.length===1?'film':'films'}`:'Sign in to personalize'}
async function createMovie(){if(!loggedIn()){openAuth();return}const value=id=>document.getElementById(id).value.trim();const payload={MovieName:value('movieName'),Genre:value('movieGenre'),Language:value('movieLanguage'),Director:value('movieDirector'),PosterUrl:value('moviePoster'),Overview:value('movieOverview'),ReleaseYear:value('movieYear'),Rating:value('movieRating')};Object.keys(payload).forEach(k=>{if(payload[k]==='')delete payload[k]});if(!payload.MovieName){notify('Movie title is required',true);return}const button=$('#addMovieButton');button.disabled=true;button.textContent='Adding…';try{await api(API_URL,{method:'POST',body:JSON.stringify(payload)});['movieName','movieGenre','movieLanguage','movieDirector','moviePoster','movieOverview','movieYear','movieRating'].forEach(id=>document.getElementById(id).value='');notify('Movie added to CineVerse');await loadMovies(true);$('#discover').scrollIntoView({behavior:'smooth'})}catch(e){notify(e.message||'Could not add movie',true)}finally{button.disabled=false;button.textContent='Add to catalog →'}}
function openAuth(){$('#authModal').classList.remove('hidden');$('#startAuth').focus()}function closeAuth(){$('#authModal').classList.add('hidden')}
async function sha256(value){const data=new TextEncoder().encode(value);return crypto.subtle.digest('SHA-256',data)}function b64url(buf){return btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}function randomString(n=64){const a=new Uint8Array(n);crypto.getRandomValues(a);return b64url(a)}
async function startAuth(){if(!cfg.cognitoDomain||!cfg.clientId){notify('Authentication is not configured for this deployment',true);return}const verifier=randomString();const state=randomString(24);sessionStorage.setItem(VERIFIER_KEY,verifier);sessionStorage.setItem(STATE_KEY,state);const challenge=b64url(await sha256(verifier));const redirect=cfg.redirectUri||location.origin+'/';const u=new URL(`${cfg.cognitoDomain.replace(/\/$/,'')}/oauth2/authorize`);u.searchParams.set('response_type','code');u.searchParams.set('client_id',cfg.clientId);u.searchParams.set('redirect_uri',redirect);u.searchParams.set('scope','openid email profile');u.searchParams.set('code_challenge_method','S256');u.searchParams.set('code_challenge',challenge);u.searchParams.set('state',state);location.assign(u)}
async function finishAuth(){const params=new URLSearchParams(location.search),code=params.get('code'),state=params.get('state');if(!code)return;if(!state||state!==sessionStorage.getItem(STATE_KEY)){notify('Sign-in verification failed',true);return}try{const verifier=sessionStorage.getItem(VERIFIER_KEY);const r=await fetch(`${cfg.cognitoDomain}/oauth2/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:cfg.clientId,code,redirect_uri:cfg.redirectUri||location.origin+'/',code_verifier:verifier})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||'Sign-in failed');sessionStorage.setItem(TOKEN_KEY,d.id_token);sessionStorage.removeItem(VERIFIER_KEY);sessionStorage.removeItem(STATE_KEY);history.replaceState({},'',location.pathname+location.hash);updateAuthUI();await loadWatchlist();notify('Welcome to CineVerse')}catch(e){notify(e.message,true)}}
function signOut(){sessionStorage.removeItem(TOKEN_KEY);watchlist.clear();updateAuthUI();renderWatchlist();renderMovies();if(cfg.cognitoDomain&&cfg.clientId){const u=new URL(`${cfg.cognitoDomain.replace(/\/$/,'')}/logout`);u.searchParams.set('client_id',cfg.clientId);u.searchParams.set('logout_uri',cfg.logoutUri||location.origin+'/');location.assign(u)}else notify('Signed out')}
function updateAuthUI(){const b=$('#authButton');const contribute=$('#contribute');if(loggedIn()){const c=claims();b.textContent=c?.email||'Account';b.onclick=signOut;contribute.classList.remove('hidden')}else{b.textContent='Sign in';b.onclick=openAuth;contribute.classList.add('hidden')}}
function reset(){['#searchInput','#genreFilter','#yearFilter','#ratingFilter','#sortFilter'].forEach((s,i)=>{const el=$(s);if(i===0)el.value='';else if(i===3)el.value='0';else if(i===4)el.value='featured';else el.value=''});applyFilters()}
$('#searchToggle').onclick=()=>{$('#searchPanel').scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>$('#searchInput').focus(),250)};$('#heroSearch').onclick=()=>{$('#searchPanel').scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>$('#searchInput').focus(),250)};$('#heroExplore').onclick=()=>$('#discover').scrollIntoView({behavior:'smooth'});$('#clearSearch').onclick=()=>{$('#searchInput').value='';applyFilters();$('#searchInput').focus()};['#genreFilter','#yearFilter','#ratingFilter','#sortFilter'].forEach(s=>$(s).addEventListener('change',applyFilters));$('#searchInput').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(applyFilters,180)});$('#resetFilters').onclick=reset;$('#retryButton').onclick=()=>loadMovies(true);$('#loadMore').onclick=()=>loadMovies(false);$('#addMovieButton').onclick=createMovie;$('#menuButton').onclick=()=>$('#mobileNav').classList.toggle('open');$('#authClose').onclick=closeAuth;$('#startAuth').onclick=startAuth;$('#dialogClose').onclick=()=>$('#movieDialog').close();$('#dialogCloseSecondary').onclick=()=>$('#movieDialog').close();$('#dialogWatchlist').onclick=()=>activeMovie&&toggleWatchlist(activeMovie.MovieId);$('#year').textContent=new Date().getFullYear();document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();$('#searchInput').focus()}if(e.key==='Escape'){closeAuth();if($('#movieDialog').open)$('#movieDialog').close()}});
finishAuth().then(()=>{updateAuthUI();loadMovies(true).then(loadWatchlist)});
