// ─── CONFIGURATION ──────────────────────────────────────────────────
// This file is generated by CD pipeline during deployment.
// DO NOT EDIT MANUALLY – it will be overwritten.
// For local development, copy config.example.js to config.js.

const API_URL = 'https://YOUR-API-ID.execute-api.us-east-1.amazonaws.com/dev/movies';