// Generated by scripts/deploy.sh or scripts/deploy.ps1. Safe placeholder for local preview.
window.CINEVERSE_CONFIG = {
  apiUrl: 'https://YOUR-API-ID.execute-api.YOUR-REGION.amazonaws.com/prod/movies',
  cognitoDomain: 'https://YOUR-COGNITO-DOMAIN.auth.YOUR-REGION.amazoncognito.com',
  clientId: 'YOUR_COGNITO_CLIENT_ID',
  redirectUri: window.location.origin + '/',
  logoutUri: window.location.origin + '/'
};
